version: '3.8'

services:
  opencontrol:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      # Optional: Mount the database for persistence
      - ./data:/app/build-schedule 